name: AmongBlocks
version: 1.0
author: Karamouche
main: fr.karamouche.amongblocks.Main
commands:
  forcestart:
    description: start the game
    permission: ab.start
  seetasks:
    description: see which tasks we have
    permission: ab.seetasks
    aliases: st